config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('', include('blogapp.urls', namespace='blogapp')),
    path('usersapp/', include('usersapp.urls', namespace='usersapp')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT))

usersapp/urls.py
from django.urls import path
from usersapp.apps import UsersappConfig
from usersapp.views import LoginView, LogoutView, RegisterView, ProfileView, activate, email_activate, restore_password

app_name = UsersappConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name = 'profile'),
    path('activate/<str:uid>/', activate, name="activate"),
    path('email_activate', email_activate, name="email_activate"),
    path('restore_password', restore_password, name="restore_password"),
]

usersapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from mainapp.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=30, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='страна', **NULLABLE )
    avatar = models.ImageField(upload_to='usersapp/', verbose_name='аватар', **NULLABLE)
    email_verify = models.IntegerField(verbose_name='код верификации email', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []



    def __str__(self):
        return  f'{self.email}'


    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

usersapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from usersapp.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone',)


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'country',)

    def __init__(self, *args, **kwargs):  # убирает информацию про кодировку пароля в профиле
        super().__init__(*args, **kwargs)
        print(self.fields)

        self.fields['password'].widget = forms.HiddenInput()

usersapp/views.py
import random
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from usersapp.forms import UserRegisterForm, UserProfileForm
from usersapp.models import User


class LoginView(BaseLoginView):
    model = User
    template_name = 'usersapp/login.html'
    # success_url = reverse_lazy('mainapp:home')

class LogoutView(BaseLogoutView):
    model = User
    # success_url = reverse_lazy('mainapp:home')


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'usersapp/register.html'
    success_url = reverse_lazy('usersapp:login')

    def form_valid(self, form):
        new_user = form.save(commit=False)
        verification = gen_verify_code()
        new_user.email_verify = verification
        new_user.is_active = False  #делаем нового юзера неактивным
        verification_url = f'http://127.0.0.1:8000/usersapp/activate/{verification}'
        send_mail(
            subject='Подтверждение адреса электронной почты',
            message=f'Для подтверждения вашей почты перейдите по ссылке: {verification_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        new_user.save()

        return super().form_valid(form)


class ProfileView (UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'usersapp/profile.html'
    success_url = reverse_lazy('mainapp:home')

    def get_object(self, queryset=None):
        return self.request.user


def email_activate(request):
    return render(request, "usersapp/email_activate.html")


def activate(request, uid):
    user = User.objects.filter(email_verify=int(uid)).first()
    user.is_active = True
    user.save()
    return redirect(reverse('mainapp:home'))


def restore_password(request):
    if request.method == "POST":
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        new_password = gen_verify_code()
        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect(reverse('usersapp:login'))
    return render(request, "usersapp/restore_password.html")


def gen_verify_code():
   return (''.join([str(random.randint(0, 9)) for i in range(4)]))

usersapp/templates/usersapp/email_activate.html
{% extends 'mainapp/base.html' %}
{% block content%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-5">Почта успешно подтверждена</h1>
    <p class="lead">Поздравляем :)</p>
</div>
{% endblock %}

usersapp/templates/usersapp/login.html
{% extends 'mainapp/base.html' %}
{% block content%}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3">
        </div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Вход
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
               <a class="p-2 btn btn-outline-primary" href="{% url 'usersapp:restore_password' %}">Восстановить пароль</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

usersapp/templates/usersapp/profile.html
{% extends 'mainapp/base.html' %}
{% block content%}


<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3">

        </div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Профиль
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

usersapp/templates/usersapp/register.html
{% extends 'mainapp/base.html' %}
{% block content%}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3">

        </div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

usersapp/templates/usersapp/restore_password.html
{% extends 'mainapp/base.html' %}
{% block content%}
<div class="container text-center">
    <div class="col-md-6 text-center">
        <div class="card mb-2 box-shadow">
            <div class="card-header">
                <h4><font color= 'green'> Восстановление пароля<font></h4>
            </div>
            <div class="card-body">
                <p class="card-text">
                <h5><font color= 'blue'>Укажите ваш email<font></h5>
                <form method="post">
                    {% csrf_token %}
                    <input class="form-control mb-2" name="email"/>
                    <button type="submit" class=" mb-2 btn btn-primary form-control">Восстановить пароль</button>
                </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}