config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('', include('blogapp.urls', namespace='blogapp')),
    path('usersapp/', include('usersapp.urls', namespace='usersapp')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT))

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig
from mainapp.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    toggle_publish

app_name = MainappConfig.name

urlpatterns = [
    path('home/', views.home, name='home'),
    path('contacts/', cache_page(30)(views.contacts), name='contacts'),
    path('list/', ProductListView.as_view(), name='list'),
    path('detail/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='detail'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('toggle/<int:pk>/', toggle_publish, name='toggle'),
]

usersapp/urls.py
from django.urls import path
from usersapp.apps import UsersappConfig
from usersapp.views import LoginView, LogoutView, RegisterView, ProfileView, activate, email_activate, restore_password

app_name = UsersappConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name = 'profile'),
    path('activate/<str:uid>/', activate, name="activate"),
    path('email_activate', email_activate, name="email_activate"),
    path('restore_password', restore_password, name="restore_password"),
]

mainapp/models.py
from django.conf import settings
from django.db import models, connection


NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(max_length=500, verbose_name='описание')


    def __str__(self):
        return f'{self.name}, {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    @classmethod
    def restart_id(cls):
        with connection.cursor() as cursor:
            cursor.execute(f'TRUNCATE mainapp_category RESTART IDENTITY CASCADE')



class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование', unique=True, **NULLABLE)
    description = models.TextField(max_length=100, verbose_name='описание')
    picture = models.ImageField(upload_to = 'mainapp', verbose_name='картинка', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=0, verbose_name='цена')
    data_life = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    data_chadge = models.DateField(**NULLABLE, verbose_name='дата_изменения')
    owner = models.ForeignKey('usersapp.User', on_delete=models.SET_NULL, verbose_name='id_пользователя', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='признак_публикации')


    def __str__(self):
        return  f'{self.name}'


    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='id_product')
    number_version = models.IntegerField(verbose_name='номер_версии')
    name = models.CharField(max_length=100, verbose_name='наименование')
    current_version = models.BooleanField(verbose_name='признак_текущей_версии')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

mainapp/forms.py
from django import forms
from mainapp.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        fields = ('name', 'description', 'category', 'picture', 'price',)
        # excude = ('is_active',)



    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        prohibited_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for obj in prohibited_list:
            if obj in cleaned_data:
                raise forms.ValidationError("Продукт запрещен на площадке")

        return cleaned_data

class ModeratorProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category',)


    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        prohibited_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for obj in prohibited_list:
            if obj in cleaned_data:
                raise forms.ValidationError("Продукт запрещен на площадке")

        return cleaned_data



class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('product', 'name', 'number_version', 'current_version',)

mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.template.context_processors import request
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from mainapp.forms import ProductForm, VersionForm, ModeratorProductForm
from mainapp.models import Product, Version


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'mainapp.add_product'
    # fields = ('name', 'description', 'category', 'picture', 'price',)
    # template_name = 'mainapp/product_form.html'
    success_url = reverse_lazy('mainapp:list')




    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, Version, form = VersionForm, extra =1)
        if self.request.method =='POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance = self.object )
        else:
            context_data['formset'] = SubjectFormset(instance = self.object)
        return context_data


    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)





class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'mainapp.change_product'
    success_url = reverse_lazy('mainapp:list')



    def get_form_class(self):
        user = self.request.user

        if user.is_staff:
            form_class = ModeratorProductForm
        else:
            form_class = ProductForm
        return form_class


    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if self.object.owner != self.request.user:
            return redirect(reverse('usersapp:login'))
        else:
            self.object.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()
            return super().form_valid(form)



class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    form_clss = ProductForm
    permission_required = 'mainapp.view_product'
    # template_name = 'mainapp/product_list.html'
    success_url = reverse_lazy('mainapp:list')

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        # queryset = queryset.filter(public_sign=True)
        return queryset


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        for product in context['object_list']:
            active_version = product.version_set.filter(current_version=True).first()

            if active_version:
                product.active_version_number = active_version.number_version
                product.active_version_name = active_version.name

            else:
                product.active_version_number = None
                product.active_version_name = None

        return context



# def products(request):
#     products_list = Product.objects.all()
#     context = {
#         'objects_list': products_list,
#         'title': 'Каталог продуктов'
#     }
#     return render(request, 'mainapp/product_list.html', context)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'mainapp/product_detail.html'
    permission_required = 'mainapp.view_product'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        product = context['object']

        active_version = product.version_set.filter(current_version=True).last()
        if active_version:
            product.active_version_number = active_version.number_version
            product.active_version_name = active_version.name
        else:
            product.active_version_number = None
            product.active_version_name = None

        return context


# def product(request, pk):
#     context = {
#         'object': Product.objects.get(pk=pk),
#         'title': 'О товаре'
#     }
#     return render(request, 'mainapp/product_detail.html', context)

class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('mainapp:list')
    permission_required = 'mainapp.delete_product'

    def get_success_url(self):
        if self.request.user == 'AnonymousUser':
            self.object.save()
            return reverse('mainapp:list')

        return reverse('usersapp:login')


def toggle_publish(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    if product_item.is_published:
        product_item.is_published = False
    else:
        product_item.is_published = True

    product_item.save()

    return redirect(reverse('mainapp:list'))


def contacts(request):
    context = {
        'title': 'Контакты'
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Все получилось contacts: {name} {phone}: {message}')

    return render(request, 'mainapp/contacts.html', context)


def home(request):
    context = {
        'title': 'Product_store'
    }
    return render(request, 'mainapp/home.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <!-- Bootstrap core CSS -->
<link href={% static 'css/bootstrap.min.css' %} rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!--"/docs/5.0/dist/css/bootstrap.min.css" -->



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Product_store</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mainapp:home' %}">Домой</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mainapp:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mainapp:list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blogapp:list' %}">Блог</a>
        </p>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'usersapp:profile' %}">Мой профиль: <font color="green" size = '3'> {{user}}</font></a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'usersapp:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'usersapp:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'usersapp:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>
{% block content%}
{% endblock %}
{% include 'mainapp/includes/inc_base_tail.html'%}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% block content%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                      <input type="submit">
                    <button class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/home.html
{% extends 'mainapp/base.html' %}
{% block content%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Product_store - это отличный вариант покупки свежих продуктов с быстрой доставкой</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Еженедельная подписка</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">200 RUB</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Бесплатная доставка</li>
                        <li>- Бесплатная сборка</li>
                        <li>- Дешевле, чем на полке</li>
                        <li>- Удобный интервал доставки</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% block content%}


    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
    </div>
    <div class="row justify-content-center">

    <div class="row text-center">
        <div class="col-5">
           <div class="card mb-4 rounded-3 shadow-sm border-primary">
              <div class="card-header py-3 text-white bg-primary border-primary">
                <h4 class="my-0 fw-normal">{{ object.name|slice:35 }}</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{object.price}}<small class="text-muted fw-light">/RUB</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ object.description|slice:100 }}</li>
                  <li>Дата поступления: {{ object.data_life}}</li>
                </ul>
                <a class="p-2 btn btn-outline-primary" href="{% url 'mainapp:products' %}">Вернуться в каталог</a>
              </div>
            </div>
        </div>
{% endblock %}

mainapp/templates/mainapp/product_confirm_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить товар "{{ object.name }}"?</p>
                            <div class="btn-group">
                                <button type="submit" class="btn btn-danger">
                                Подтвердить
                                </button>
                                <a href="{% url 'mainapp:list' %}" type="button"
                                   class="btn btn-outline-warning">Назад</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% block content%}


    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
    </div>
    <div class="row justify-content-center">

    <div class="row text-center">
        <div class="col-6">
           <div class="card mb-4 rounded-3 shadow-sm border-primary">
              <div class="card-header py-3 text-white bg-primary border-primary">
                <h4 class="my-0 fw-normal">{{ object.name|slice:35 }}</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{object.price}}<small class="text-muted fw-light">/RUB</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ object.description|slice:100 }}</li>
                  <li>Дата поступления: {{ object.data_life}}</li>
                </ul>
              </div>
              <div class="card-body">
                  <ul class="list-unstyled mt-3 mb-4">
                  <li>Номер активной версии<small class="text-muted fw-light"> <font color="blue" size = '3'>/ {{ object.active_version_name }}</font></small></li>
                  <li>Активная версия<small class="text-muted fw-light"><font color="blue" size = '3'>/ {{ object.active_version_number }}</font></small></li>
                  <li>Продукт создал<small class="text-muted fw-light"><font color="blue" size = '3'>/ {{ object.owner }}</font></small></li>
                </ul>
              </div>
                <a class="p-2 btn btn-outline-primary" href="{% url 'mainapp:list' %}">Вернуться в каталог</a>
              </div>
            </div>
        </div>
{% endblock %}

mainapp/templates/mainapp/product_form.html
{% extends 'mainapp/base.html' %}

{% block content %}
<form method="post">
    <div class="col-12"><div/>
        <div class="row">
            <div class="col-6">
                <div class="card">
                     <div class="card-header">
                     <h2>Введите данные продукта</h2>
                     <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        </div>
                    </div>
                    <div class="btn-group">
                    <button type="submit" class="btn btn">
                           {% if object.is_published %}
                           <a class="p-1 btn btn-outline-danger" href="{% url 'mainapp:toggle' object.pk %}">Cкрыть видимость</a>
                           {% else %}
                           <a class="p-1 btn btn-outline-success">Опубликовать</a>
                           {% endif %}
                    </div>
                </div>
              </div>

            <div class="col-6">
                <div class="card">
                {% if not user.is_staff %}
                     <div class="card-header">
                     <h2>Введите данные версии </h2>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{form.as_p}}
                {% endfor %}
            </div>
            {% endif%}
                <div class="btn-group">
                    <button type="submit" class="btn btn-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                    </button>
                    <a href="{% url 'mainapp:list' %}" type="button"
                    class="btn btn-outline-secondary">Назад</a>
                </div>
            </div>
         </div>
    </div>
</div>
</form></div>
{% endblock %}

mainapp/templates/mainapp/product_list.html
{% extends 'mainapp/base.html' %}
{% block content%}

    {% load static %}
    {% load my_tags_lib %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
    </div>
    <div class="row justify-content-center">


    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
               </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="card shadow-sm">
                    </div>
                    {% if not user.is_staff %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'mainapp:create' %}">Создать продукт</a>
                    {% endif%}
                        <div class="card mb-6 box-shadow">
                           {% for object in object_list %}
                            {% if object.active_version_number != None and object.is_published %}

                            <p><div class="card-body">
                                </div>
                              <img class="card-img-top"
                                 src="/media/{{ object.picture }}">
                                 <alt="Card image cap">
                                <p class="card-text ms-3"><font color="green" size = '4'>{{ object|title }}<font>
                                <button type="button" class="btn btn-sm btn-outline-secondary"><font color="green" size = '3'>{{object.price}}<font></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"><font color="green" size = '3'>RUB<font></button></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group ms-3" >
                                        <a class="p-1 btn btn-outline-primary" href="{% url 'mainapp:detail' object.pk %}">О товаре</a>
                                        <a class="p-1 btn btn-outline-primary" href="{% url 'mainapp:update' object.pk %}">Изменить товар</a>
                                        {% if not user.is_staff %}
                                        <a class="p-1 btn btn-outline-danger" href="{% url 'mainapp:delete' object.pk %}">Удалить товар</a>
                                        {% endif%}
                                    </div>

                                </div>
                             {% else %}

                              <p><div class="card mb-6 box-shadow">
                                 <div class="card-body">
                                </div>
                                 <img class="card-img-top"
                                 src="/media/{{ object.picture }}">
                                 <alt="Card image cap">
                                <p class="card-text ms-3"><font color="gray" size = '3'>{{ object|title }}
                                <button type="button" class="btn btn-sm btn-outline-secondary">Не опубликовано</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">RUB </button></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group ms-3" >
                                        <a class="p-1 btn btn-outline-secondary" href="{% url 'mainapp:detail' object.pk %}">О товаре</a>
                                        <a class="p-1 btn btn-outline-secondary" href="{% url 'mainapp:update' object.pk %}">Изменить товар</a>
                                        {% if not user.is_staff %}
                                        <a class="p-1 btn btn-outline-secondary" href="{% url 'mainapp:delete' object.pk %}">Удалить товар</a>
                                        {% endif%}
                                    </div>

                                </div></p>

                            {% endif %}
                           {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}