blogapp/urls.py
from django.urls import path

from blogapp import views
from blogapp.apps import BlogappConfig
from blogapp.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_publish

app_name = BlogappConfig.name

urlpatterns = [
    path('blogapp/create/', BlogCreateView.as_view(), name='create'),
    path('blogapp/list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('blogapp/update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('blogapp/delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('blogapp/toggle/<int:pk>/', toggle_publish, name='toggle'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('', include('blogapp.urls', namespace='blogapp')),
    path('usersapp/', include('usersapp.urls', namespace='usersapp')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT))

blogapp/models.py
from django.db import models


NULLABLE = {'null': True, 'blank': True}

class Blog(models.Model):
    header = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='слаг')
    blog_content = models.TextField(max_length=500, verbose_name='содержимое')
    picture = models.ImageField(upload_to = 'blogapp', verbose_name='картинка', **NULLABLE)
    data_life = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    public_sign = models.BooleanField(default=True, verbose_name='признак_публикации')
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')


    def __str__(self):
        return  f'{self.header}'


    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blogapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blogapp.models import Blog
from pytils.translit import slugify


class BlogCreateView(CreateView):
    model = Blog
    fields = ('header', 'blog_content',)
    success_url = reverse_lazy('blogapp:list')


    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.header)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    success_url = reverse_lazy('mainapp:home')

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        # queryset = queryset.filter(public_sign=True)
        return queryset



class BlogDetailView(DetailView):
    model = Blog
    success_url = reverse_lazy('blogapp:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views +=1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('header', 'blog_content', 'public_sign',)
    success_url = reverse_lazy('blogapp:list')


    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.header)
            new_blog.save()

        return super().form_valid(form)


    def get_success_url(self):
        return reverse('blogapp:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogapp:list')


def toggle_publish(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.public_sign:
        blog_item.public_sign = False
    else:
        blog_item.public_sign = True

    blog_item.save()

    return redirect(reverse('blogapp:list'))

blogapp/templates/blogapp/blog_confirm_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью "{{ object.header }}"?</p>
                            <div class="btn-group">
                                <button type="submit" class="btn btn-danger">
                                Подтвердить
                                </button>
                                <a href="{% url 'blogapp:list' %}" type="button"
                                   class="btn btn-outline-warning">Назад</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogapp/templates/blogapp/blog_detail.html
{% extends 'mainapp/base.html' %}

{% block content %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Blog Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
  </head>
  <body>

<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Подписаться</a>
      </div>
    </div>
  </header>



<main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">{{object| title}}</h1>

    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">

    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        </div>
        <div class="col-auto d-none d-lg-block">

        </div>
      </div>
    </div>
  </div>

  <div class="row g-5">
    <div class="col-md-8">


      <article class="blog-post">
        <h2 class="blog-post-title">{{object.header}}</h2>
        <p class="blog-post-meta">{{object.data_life }} by <a href="#">Mark</a></p>

        <p>{{object.blog_content }}</p>
        <hr>


      <article class="blog-post">
     </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">Об авторе</h4>
          <p class="mb-0">Очень много хороших слов про автора.</p>
        </div>
        <div class="card-footer">
          Просмотры: {{object.number_of_views}}
        </div>
        <div class="card-footer">
          Слаг: {{object.slug}}
      </div>
    </div>
  </div>

</main>

  </body>
</html>
{% endblock %}

blogapp/templates/blogapp/blog_form.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <div class="col-12"><div/>
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="btn-group">
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                                <a href="{% url 'blogapp:list' %}" type="button"
                                   class="btn btn-outline-secondary">Назад</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogapp/templates/blogapp/blog_list.html
{% extends 'mainapp/base.html' %}
{% block content%}

    {% load static %}
    {% load my_tags_lib %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ header }}</h1>
    </div>
    <div class="row justify-content-center">


    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
               </div>
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="card shadow-sm">
                    </div>
                     <a class="p-2 btn btn-outline-primary" href="{% url 'blogapp:create' %}">Создать статью</a>


                        <div class="card mb-6 box-shadow">
                           {% for object in object_list %}
                            <div class="card-body">
                                </div>
                              <img class="card-img-top"
                                 src="/media/{{ object.picture }}">
                                 <alt="Card image cap">
                                <p class="card-text">{{ object|title }}.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="p-1 btn btn-outline-primary" href="{% url 'blogapp:view' object.pk %}">Прочитать статью</a>
                                        <a class="p-1 btn btn-outline-primary" href="{% url 'blogapp:update' object.pk %}">Редактировать статью</a>
                                        <a class="p-1 btn btn-outline-danger" href="{% url 'blogapp:delete' object.pk %}">Удалить статью</a>
                                    </div>

                                    </div>
                                    {% if object.public_sign %}
                                    <a class="p-1 btn btn-outline-danger" href="{% url 'blogapp:toggle' object.pk %}">Убрать видимость</a>
                                    {% else%}
                                    <a class="p-1 btn btn-outline-success" href="{% url 'blogapp:toggle' object.pk %}">Сделать видимой</a>
                                    {% endif%}
                              </div>
                                {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}